# Generated by Django 4.2.10 on 2024-02-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_status',
            field=models.CharField(default='Not Paid', max_length=100),
        ),
    ]
